---
# tasks file for nodejs
- name: download nodejs from source
  unarchive:
    src: https://nodejs.org/dist/v20.20.0/node-v20.20.0-linux-x64.tar.xz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/node-v20.20.0-linux-x64

- name: symlink node
  file:
    src: /usr/local/node-v20.20.0-linux-x64/bin/node
    dest: /usr/local/bin/node
    state: link

- name: symlink npm
  file:
    src: /usr/local/node-v20.20.0-linux-x64/bin/npm
    dest: /usr/local/bin/npm
    state: link

- name: install yarn via npm
  shell: npm install -g yarn
  args:
    creates: /usr/local/node-v20.20.0-linux-x64/bin/yarn

- name: symlink yarn
  file:
    src: /usr/local/node-v20.20.0-linux-x64/bin/yarn
    dest: /usr/local/bin/yarn
    state: link